### ISSUE TITLE
i met the same issue

### ISSUE THREAD

**Issue by zhongxx0227** [k0rnh0li0/onlyfans-dl#162]
Okay, i have solutioned, thks, but now i have an other error xddd

"ERROR: Access denied."

What can i do? Thanks ans sorry for disturb

_Originally posted by @IceTorch66 in https://github.com/k0rnh0li0/onlyfans-dl/issues/155#issuecomment-1017290574_

**Comment by fahq613** [comment]
In my experience this is because you need to update your auth file with new values due to a new login to onlyfans.  I could be wrong but i think its only sess that changes.

**Comment by blmatthews** [comment]
That should always be the first step, redo the auth file, and if that doesn't work, double check your work. Also, if you update your browser (which Chrome does automatically without notice, Firefox can do if you've got a preference set to do so, and Safari will often get updated with other system updates (and presumably IE on Windows)), the User-Agent string may change, so make sure to check that, don't just assume that because you haven't manually updated your browser it hasn't changed.
