### ISSUE TITLE
Newly updated values then logout

### ISSUE THREAD

**Issue by agentlemonz** [k0rnh0li0/onlyfans-dl#175]
The program keeps crashing. I updated all values in auth file and then open the .py file and crashes after second "x"

Once I run program I am auto logged out of OF on my browser
Log back in and update new values however process repeats

**Comment by Jekotia** [comment]
So, let's work backwards a bit to understand what's going on here.

My best guess is that this is a security feature on OnlyFan's end: if a single value in the auth file is wrong other than the sess cookie, that sess cookie becomes invalidated on OF's end. When your browser tries to reconnect using that sess cookie, OF goes NOPE, SIGN BACK IN. This is why you keep being signed out in your browser.

Because of this, I strongly suspect that the program is not crashing, but instead it is failing to authenticate because one of your values is incorrect. Since it sounds like you're double-clicking on the python script, the python executable immediately closes when it's finished running.

I would recommend launching the python script from a terminal. This will prevent it from immediately closing, and allow you to see what is causing it to complete. If it is indeed an authentication problem, here's how I would recommend going about this:

1. Follow the directions to get your useragent
2. Follow the directions to get your user-id (this NEVER changes, this is associated with your account)
3. Follow the directions to get your x-bc (I don't _think_ this changes every time, but I can't say with certainty)
4. Finally, follow the directions to get your sess cookie value (this changes every single time you login, no exceptions)
5. Launch onlyfans-dl.py

**Comment by dinosaw** [comment]
@Jekotia 

Thanks for that rundown. I was curious if you're able to help me as I have a similar problem as the OP. Basically the Python script is unsuccessful (I get the `Error: Access Denied`) and then the actual OF website logs me out. I agree about your theory regarding OF's security measure and that it forces you to sign back in if there is something wrong in the auth file.

The only problem I'm running into is that - I'm using the correct auth file values. Basically, I do a cache refresh of the page, check the Network tab, filter for `api`, select the `init` source, which gives you something that looks like the following:

```
cookies: csrf=XXXXX; fp=XXXXX; ref_src=; auth_id=XXXXX; cookiesAccepted=true; sess=XXXXX; st=XXXXX
```
Just from that, you can get the `user-id` (or `auth_id`, and you're correct, this doesn't change), and the `sess` key. As far as the `x-bc` value, if you scroll down the init file to the bottom, you will see where it says:

```
x-bc: XXXXXXXXXXXXXXXXXXXXXXX
```

Using all this information, my `auth.json` file looks like this:

```json
{
        "user-agent": "Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
        "user-id": "XXXXXX",
        "sess": "XXXXXX",
        "x-bc": "XXXXXX"
}
```

Then when using Python (3.9.10) and running `./onlyfans-dl.py`, as I stated prior, it just says Access Denied and the script quits, and I'm logged out of the OF website.

I'm utterly confused because I have checked and rechecked I'm using the correct values, I've used incognito windows and normal windows, and I've grabbed the cookie data from both Chrome and Firefox. Each time making sure to have the most up to date cookie information (because it looks like the `sess` key is what changes the most ofen) and still continuously get authorization issues.

Is there anything you can think of that I might be doing wrong?

**Comment by BrianLMatthews** [comment]
There's no Browser: at the start of any user agent I've ever seen. Try removing that, so your user agent starts with "Mozilla/5.0..."

**Comment by agentlemonz** [comment]
Thanks @Jekotia 
btw I'm using Firefox, have also tested with chrome. You're right it was not crashing I opened via teminal and was getting `Access Denied`

I played around a bit and it was indeed an incorrect value in the `auth` file. The `user-agent` was incorrect, i was using IP chicken and other random websites to grab my `user-agent` which is what I think may have been the issue because as soon as I got the value via the Dev tools in firefox it would work as per below
![image](https://user-images.githubusercontent.com/95955534/165947100-6833ee98-7dd5-4754-8105-29d6e87ed6e1.png)
Then under headers tab at the bottom:
![image](https://user-images.githubusercontent.com/95955534/165947291-2590e36a-8db5-40be-9c29-2c274d27f173.png)


1. Log in to OF as normal
2. Get the `x-bc` and `user-id` first
3. Log out then log back into the homepage
4. Grab the `sess` value
5. Run the .py file
