### ISSUE TITLE
ERROR: Please refresh the page

### ISSUE THREAD

**Issue by Kubson11** [k0rnh0li0/onlyfans-dl#237]
i have error ERROR: Please refresh the page what i need do

**Comment by anotherguy31** [comment]
I got the same error since yesterday, probably Onlyfans changed the authentication method :/ 
This project will not receive any updates anymore, so it's best search for another app.

There is an extension on google chrome called 'Downloader for Onlyfans.com' that allows you to download the posts, but you will have to download them one by one, if the post has 20 images it can download the 20 at once.

I think this is the end :'(

**Comment by blmatthews** [comment]
There's also https://github.com/Voldrix/onlyfans-dl-2, which was just updated a couple of days ago and worked for me just now. Maybe you could apply the same fix to this script.

**Comment by mangoarctic21** [comment]
Since I prefer this version versus Voldrix's, I decided to dig a little bit and found the problem. Voldrix's version also encountered this issue, but they have since been able to resolve it. Just need to open the onlyfans-dl.py file and change:
'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
to
'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()

**Comment by Kubson11** [comment]
i tried to use it and i get only something like this Downloading content to <profile_name> and program dont do anything more dont downloading/creating nothing my profile is small but program working 2h and dont do anything

**Comment by SirAeleon** [comment]
> Since I prefer this version versus Voldrix's, I decided to dig a little bit and found the problem. Voldrix's version also encountered this issue, but they have since been able to resolve it. Just need to open the onlyfans-dl.py file and change: 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json() to 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()

Thank you good sir!

**Comment by kusti420** [comment]
> I got the same error since yesterday, probably Onlyfans changed the authentication method :/ This project will not receive any updates anymore, so it's best search for another app.
> 
> There is an extension on google chrome called 'Downloader for Onlyfans.com' that allows you to download the posts, but you will have to download them one by one, if the post has 20 images it can download the 20 at once.
> 
> I think this is the end :'(

big yikes

**Comment by iansquenet** [comment]
Both seem to give the 404.

**Comment by blmatthews** [comment]
> Both links seem to give the 404.

Are you clicking the links here? Because github includes an extraneous `').json()` on the end which will make the links return a 404. If you copy and try just the stuff in single quotes, they both work fine, as does the script when the change is properly applied.

**Comment by KharonStyx** [comment]
> 

This worked for me. Was wondering for ages if it was a wrong auth file etc.

**Comment by jordon31** [comment]
my script its better

https://github.com/jordon31/OF-SCR

**Comment by Kubson11** [comment]
> my script its better
> 
> https://github.com/jordon31/OF-SCR

nice work man

**Comment by jordon31** [comment]
> > my script its better
> > https://github.com/jordon31/OF-SCR
> 
> nice work man

Thanks

**Comment by sotugas** [comment]
> > Since I prefer this version versus Voldrix's, I decided to dig a little bit and found the problem. Voldrix's version also encountered this issue, but they have since been able to resolve it. Just need to open the onlyfans-dl.py file and change:
> > 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
> > to
> > 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
> 
> This worked for me. Was wondering for ages if it was a wrong auth file etc.

It worked for a while but now it's not working again.
Any clue?

**Comment by dfjeiwn** [comment]
It's still not working for me. I now use the free trial version of [OnlyfFans downloader](https://streamfab.tv/onlyfans-downloader.htm)
