### ISSUE TITLE
Upgrade: Multithreading

### ISSUE THREAD

**Issue by ontionas** [k0rnh0li0/onlyfans-dl#51]
I want faster download times so I am going to mess around with multithreading. I've already gotten a user's download time from about 86 seconds to 36 seconds, so that is a pretty good decrease

I think I can increase the speed of the `FInding photos...` part of the code because a bunch of time is spent waiting for the server to respond.

I'll post some updates here and link the PR when I make it.

**Comment by ontionas** [comment]
Don't really know what is going on with the pagination so I may wait to implement that. Any insights on how to adapt that to multithreading?

**Comment by ontionas** [comment]
e.g. I was just able to rip 2,015 images from a user's profile in about 2.5 minutes

These changes have necessitated some changes to the download visual feedback, which I changed to a tqdm loading bar

**Comment by k0rnh0li0** [comment]
This is a great idea, I'd be interested to follow your progress. I didn't write the pagination scheme, it was submitted in a PR, but it's basically a way of splitting a user's posts up due to API limitations. I bet it would be really great for multithreading, you could have separate threads downloading each "page" or something like that.

Cool idea!!

**Comment by dimer191996** [comment]
Getting user auth info...
Getting target profile info...

onlyfans-dl is downloading content to profiles/theonlyhydro_vids!


Profiles/theonlyhydro_vids exists.
Media already present will not be re-downloaded.
Saving profile info...
Finding photos... Found 0 photos.
Finding videos... Found 0 videos.
Finding archived content... Found 0 archived posts.
ERROR: 0 posts found.

any idea wt. is goin on
