### ISSUE TITLE
ERROR: Access Denied.

### ISSUE THREAD

**Issue by dodecaphone** [k0rnh0li0/onlyfans-dl#88]
executing "onlyfans-dl.py  user accesstoken" is returning "ERROR: Access Denied" and auto-logging out of account.

![image](https://user-images.githubusercontent.com/20006508/115796574-e8b42f80-a386-11eb-8dce-02c42454c5dd.png)

**Comment by Eviepayne** [comment]
read the readme
make sure your browser useragent is correct

**Comment by dodecaphone** [comment]
Had already updated u-a when new Firefox came out; Read readme multiple times; same result.

**Comment by Eviepayne** [comment]
Try using my fork: https://github.com/Eviepayne/onlyfans-dl
It's a bit easier to use. Make sure to read the read me since my fork works a bit different.
And every time you get access denied make sure to login again to get a new token.
It could be you're using an old version that hasn't updated to the API endpoint.

**Comment by dodecaphone** [comment]
Thank you. I'll use your fork!

**Comment by r56789-svg** [comment]
The issue is not fixed with your fork (also, why not doing a PR to this repo instead creating a new one?). The issue is that the v2 api is not being used anymore.

**Comment by dodecaphone** [comment]
Actually, this fork does work and solved the issue. I haven't had any problems since switching over from the original to Eviepayne's.

**Comment by Eviepayne** [comment]
> The issue is not fixed with your fork (also, why not doing a PR to this repo instead creating a new one?). The issue is that the v2 api is not being used anymore.

There is a pull request. It just hasn't been merged yet.

> Actually, this fork does work and solved the issue. I haven't had any problems since switching over from the original to Eviepayne's.

The only difference between origin and my fork is that mine uses a configuration file instead of CLI arguments.
Both work, it just changes how you put in certain details.
With origin you need to change the script itself and enter your token into the 3rd arg, mine you put everything in the config file and update the config file when your token changes.
As an added bonus because of that change, on my fork you can easily update by doing a git pull.

**Comment by k0rnh0li0** [comment]
didn't mean to delete ur comment sorry brother
